name: CI Check JaCoCo code-coverage

on:
  pull_request:
    branches: [ master ]

env:
  scalaLong: 2.13.11
  scalaShort: "2.13"
  REPORT_GROUPS: |
    - name: statusboard
      paths:
        - '**/target/**/jacoco-report/jacoco.xml'
      thresholds: '77*80*60'

jobs:
  detect:
    name: Detect Changed Files
    runs-on: ubuntu-latest
    timeout-minutes: 2
    outputs:
      scala_changed: ${{ steps.filter.outputs.scala }}
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d
        id: filter
        with:
          token: ""
          filters: |
            scala:
              - '**/*.scala'
              - '!project/**'

  build-test-and-measure:
    name: Build, Test and Measure
    needs: detect
    if: needs.detect.outputs.scala_changed == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write
    services:
      dynamodb-local:
        image: "amazon/dynamodb-local:latest"
        ports:
          - "8000:8000"

    steps:
      - name: Checkout code
        id: code-checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
        with:
          persist-credentials: false

      - name: Setup JVM and SBT
        id: jvm-setup
        uses: coursier/setup-action@fd1707a76b027efdfb66ca79318b4d29b72e5a02
        with:
          jvm: corretto:21.0.2.13.1
          apps: sbt

      - name: Build and run tests with test coverage
        id: jacoco-run
        continue-on-error: true
        run: sbt jacoco
        env:
          AWS_REGION: "ignored"
          AWS_ACCESS_KEY_ID: "ignored"
          AWS_SECRET_ACCESS_KEY: "ignored"

      - name: Setup Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
        with:
          python-version: '3.14'

      - name: Check coverage thresholds and add reports in PR comments
        id: jacoco
        uses: MoranaApps/jacoco-report@69351d88d18f7697c416e1bc2020ed05606d8120
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
          global-thresholds: '77*80'
          report-thresholds-default: '0*0*0'
          skip-unchanged: 'true'
          evaluate-unchanged: 'false'
          report-groups: ${{ env.REPORT_GROUPS }}

  noop:
    name: No Operation
    needs: detect
    if: needs.detect.outputs.scala_changed != 'true'
    runs-on: ubuntu-latest
    steps:
      - run: echo "No changes in src/**/*.scala — passing."
