name: Status Board - Tests with JaCoCo report

on:
  workflow_dispatch:

jobs:
  checkrunner: 
    name: Workflow test
    runs-on: ubuntu-latest
    steps:
      - name: Check
        run: echo "Runner ${{ runner.environment }}"
        shell: bash